/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import data.*;
import entidades.*;
import java.util.ArrayList;
import java.util.List;

public class AgregarHabitacion extends javax.swing.JInternalFrame {

    private Conexion con = new Conexion("jdbc:mariadb://localhost:3306/elgranhotel", "root", "");
    private Habitacion_data hd = new Habitacion_data(con);    
    private TipoHabitacion_data thd = new TipoHabitacion_data(con);
    
    
    /**
     * Creates new form AgregarHabitacion
     */
    public AgregarHabitacion() {
        initComponents();
        cargarUltHab();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtPiso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtHab = new javax.swing.JLabel();
        jcbTipoHab = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtTipoHab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtCantHues = new javax.swing.JLabel();
        jtTipoCama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtCantCama = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Tipo de Habitación");

        jtPiso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtPiso.setText(" - ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Habitación:");

        jtHab.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtHab.setText(" - ");

        jcbTipoHab.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jcbTipoHab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoHabItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Piso:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Tipo:");

        jtTipoHab.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtTipoHab.setText(" - ");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Cantidad de Huespedes:");

        jtCantHues.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtCantHues.setText(" - ");

        jtTipoCama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtTipoCama.setText(" - ");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Cama/s:");

        jtCantCama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtCantCama.setText(" - ");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Tipo de cama:");

        jButton1.setText("Agregar Habitacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(jcbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtTipoHab))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtCantCama)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jtTipoCama))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jtCantHues))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPiso)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtHab)))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPiso)
                    .addComponent(jLabel3)
                    .addComponent(jtHab)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTipoHab)
                    .addComponent(jLabel5)
                    .addComponent(jtCantHues)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCantCama)
                    .addComponent(jLabel7)
                    .addComponent(jtTipoCama)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoHabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoHabItemStateChanged
        TipoHabitacion th = new TipoHabitacion();
        th = (TipoHabitacion)jcbTipoHab.getSelectedItem();
        
        jtTipoHab.setText(th.getTipo());
        jtCantHues.setText(""+th.getCantidadPersonas());
        jtCantCama.setText(""+th.getCantidadCamas());
        jtTipoCama.setText(th.getTipoCamas());
        
    }//GEN-LAST:event_jcbTipoHabItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<TipoHabitacion> jcbTipoHab;
    private javax.swing.JLabel jtCantCama;
    private javax.swing.JLabel jtCantHues;
    private javax.swing.JLabel jtHab;
    private javax.swing.JLabel jtPiso;
    private javax.swing.JLabel jtTipoCama;
    private javax.swing.JLabel jtTipoHab;
    // End of variables declaration//GEN-END:variables

    public void cargarUltHab(){
        Habitacion ultHab = (Habitacion) hd.listarHabitaciones().get(hd.listarHabitaciones().size()-1);
        if (ultHab.getNroHabitacion() == 20) {
            jtPiso.setText(""+(ultHab.getPiso()+1));
            jtHab.setText("1");
        }else{
            jtPiso.setText(""+ultHab.getPiso());
            jtHab.setText(""+ultHab.getNroHabitacion());
        }
    }
    
    public void cargarCombo(){
        List<TipoHabitacion> listatipo = new ArrayList<>();
        
        listatipo = thd.listaTipoHab();
        
        for(TipoHabitacion tipo : listatipo){
            jcbTipoHab.addItem(tipo);
        }
        
        //jcbTipoHab.setSelectedIndex(-1);
    }

}
