/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import data.*;

import entidades.*;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BuscarReservas extends javax.swing.JInternalFrame {

    Conexion con = new Conexion("jdbc:mariadb://localhost:3306/elgranhotel", "root", "");
    Huesped_data hd = new Huesped_data(con);
    Habitacion_data habD = new Habitacion_data(con);
    Reserva_data rd = new Reserva_data(con);

    DefaultTableModel modeloH = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

    };

    public BuscarReservas() {
        initComponents();
        cargarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtRHuesped = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jdIngreso = new com.toedter.calendar.JDateChooser();
        jdEgreso = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jtDNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PanelHuesped = new javax.swing.JPanel();
        jbCancelarR = new javax.swing.JButton();

        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(1117, 875));

        jtRHuesped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtRHuesped);

        jLabel6.setText("Y:");

        jLabel5.setText("Entre:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dni.png"))); // NOI18N

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDNIKeyPressed(evt);
            }
        });

        jLabel1.setText("DNI:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jdIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                    .addComponent(jdEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jbBuscar)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jdEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jdIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBuscar)
                        .addComponent(jLabel1))
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        jbCancelarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        jbCancelarR.setText("Cancelar Reserva");
        jbCancelarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHuespedLayout = new javax.swing.GroupLayout(PanelHuesped);
        PanelHuesped.setLayout(PanelHuespedLayout);
        PanelHuespedLayout.setHorizontalGroup(
            PanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHuespedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbCancelarR))
        );
        PanelHuespedLayout.setVerticalGroup(
            PanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHuespedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCancelarR, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        borrarFilas(modeloH);
        LocalDate ingreso = null, egreso = null;
        List<ReservaHuesped> listaReservas = rd.listarReservas();

        if (jdEgreso.getDate() == null) {
            egreso = LocalDate.MAX;
        }
        if (jdIngreso.getDate() == null) {
            ingreso = LocalDate.MIN;
        } else {
            ingreso = jdIngreso.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            egreso = jdEgreso.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        for (ReservaHuesped reserva : listaReservas) {

            if (reserva.getIdHuesped().getDni().equals(jtDNI.getText()) && (reserva.getFechaIngreso().isAfter(ingreso) && reserva.getFechaSalida().isBefore(egreso)) && reserva.isEstado()) {
                modeloH.addRow(new Object[]{
                    reserva.getIdHuesped().getDni(), reserva.getIdReserva(),
                    reserva.getFechaIngreso(), reserva.getFechaSalida(),
                    reserva.getIdHabitacion().getPiso(), reserva.getIdHabitacion().getNroHabitacion(),
                    reserva.getMonto()
                });

            } else if (jtDNI.getText().equals("") && reserva.getFechaIngreso().isAfter(ingreso) && reserva.getFechaSalida().isBefore(egreso) || reserva.getFechaIngreso().isEqual(ingreso) || reserva.getFechaSalida().isEqual(egreso)) {

                modeloH.addRow(new Object[]{
                    reserva.getIdHuesped().getDni(), reserva.getIdReserva(),
                    reserva.getFechaIngreso(), reserva.getFechaSalida(),
                    reserva.getIdHabitacion().getPiso(), reserva.getIdHabitacion().getNroHabitacion(),
                    reserva.getMonto()
                });

            }

        }


    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarRActionPerformed

        if (jtRHuesped.getSelectedRowCount() > 0) {

            int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas eliminar el archivo?", "Confirmación", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                System.out.println(modeloH.getValueAt(jtRHuesped.getSelectedRow(), 1).toString());
                rd.cancelarReserva(Integer.parseInt(modeloH.getValueAt(jtRHuesped.getSelectedRow(), 1).toString()));
                modeloH.removeRow(jtRHuesped.getSelectedRow());

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una reserva");
        }


    }//GEN-LAST:event_jbCancelarRActionPerformed

    private void jtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDNIKeyPressed
        if (Character.isDigit(evt.getKeyChar()) || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {

            jtDNI.setEditable(true);

        } else {

            jtDNI.setEditable(false);
        }
    }//GEN-LAST:event_jtDNIKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHuesped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelarR;
    private com.toedter.calendar.JDateChooser jdEgreso;
    private com.toedter.calendar.JDateChooser jdIngreso;
    private javax.swing.JTextField jtDNI;
    private javax.swing.JTable jtRHuesped;
    // End of variables declaration//GEN-END:variables

    private void cargarCabecera() {
        modeloH.addColumn("DNI");
        modeloH.addColumn("ID Reserva");
        modeloH.addColumn("Ingreso");
        modeloH.addColumn("Salida");
        modeloH.addColumn("Piso");
        modeloH.addColumn("N°Habitacion");
        modeloH.addColumn("Precio");
        jtRHuesped.setModel(modeloH);

    }

    public void borrarFilas(DefaultTableModel modelo) {
        int f = modelo.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }

    }
}
