/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import data.Conexion;
import data.User_data;
import entidades.User;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CambiarPass extends javax.swing.JInternalFrame {

    Conexion con = new Conexion("jdbc:mariadb://localhost:3306/elgranhotel", "root", "");
    User_data usd=new User_data(con);
    String stringUser=Login.user;
    User user=null;
    
    public CambiarPass() {
        initComponents();
        jbEstablecerNuevaPass.setEnabled(false);
        jtNuevaContraseña.setEditable(false);
        user=buscarUser(stringUser);
        jlPreguntaBD.setText(user.getPregunta());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlPreguntaBD = new javax.swing.JLabel();
        jtRespuesta = new javax.swing.JTextField();
        jbVerificarRespuesta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNuevaContraseña = new javax.swing.JTextField();
        jbEstablecerNuevaPass = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jlPreguntaBD.setBackground(new java.awt.Color(51, 51, 51));
        jlPreguntaBD.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        jlPreguntaBD.setForeground(new java.awt.Color(255, 255, 255));
        jlPreguntaBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jtRespuesta.setBackground(new java.awt.Color(102, 102, 102));
        jtRespuesta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtRespuesta.setForeground(new java.awt.Color(0, 0, 0));
        jtRespuesta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbVerificarRespuesta.setBackground(new java.awt.Color(102, 102, 102));
        jbVerificarRespuesta.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbVerificarRespuesta.setForeground(new java.awt.Color(0, 0, 0));
        jbVerificarRespuesta.setText("Verificar");
        jbVerificarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerificarRespuestaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva contraseña:");

        jtNuevaContraseña.setBackground(new java.awt.Color(102, 102, 102));
        jtNuevaContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtNuevaContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jtNuevaContraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbEstablecerNuevaPass.setBackground(new java.awt.Color(102, 102, 102));
        jbEstablecerNuevaPass.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbEstablecerNuevaPass.setForeground(new java.awt.Color(0, 0, 0));
        jbEstablecerNuevaPass.setText("Guardar cambios");
        jbEstablecerNuevaPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstablecerNuevaPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jbEstablecerNuevaPass, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbEstablecerNuevaPass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbVerificarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlPreguntaBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlPreguntaBD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbVerificarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVerificarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerificarRespuestaActionPerformed
        
        if(user.getRespuesta().equals(jtRespuesta.getText())){
            
            JOptionPane.showMessageDialog(null, "Repuesta correcta. Proceda a cambiar la contraseña");
        
            jtNuevaContraseña.setEditable(true);
            jbEstablecerNuevaPass.setEnabled(true);
            
        }else{
        
            JOptionPane.showMessageDialog(null, "Respuesta incorrecta. Intente nuevamente");
            
        }
    }//GEN-LAST:event_jbVerificarRespuestaActionPerformed

    private void jbEstablecerNuevaPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstablecerNuevaPassActionPerformed
        usd.modificarPass(stringUser, jtNuevaContraseña.getText());
        this.setVisible(false);
        
    }//GEN-LAST:event_jbEstablecerNuevaPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbEstablecerNuevaPass;
    private javax.swing.JButton jbVerificarRespuesta;
    private javax.swing.JLabel jlPreguntaBD;
    private javax.swing.JTextField jtNuevaContraseña;
    private javax.swing.JTextField jtRespuesta;
    // End of variables declaration//GEN-END:variables

    
    public User buscarUser(String userIngresado){
    
        List<User>userList=usd.listarUsers();
    
        User user=null;
        
        for(User u:userList){
        if(u.getUser().equals(userIngresado)){
            user=new User();
            user.setUser(u.getUser());
            user.setPass(u.getPass());
            user.setPregunta(u.getPregunta());
            user.setRespuesta(u.getRespuesta());
            break;
        }
        }
        
        return user;

    }
}
