/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Usuario
 */
public class Habitacion_vista extends javax.swing.JInternalFrame {

   
    GestionHabitacion panelGH = new GestionHabitacion();
    GestionPrecio panelGP = new GestionPrecio();
    ListarHabitacion panelLH = new ListarHabitacion();
    
    
    public Habitacion_vista() {
        initComponents();
        PanePrincipal.addTab("Gestionar Habitaciones",panelGH);
        PanePrincipal.addTab("Gestionar Precios",panelGP);
        PanePrincipal.addTab("Listar Habitaciones", panelLH);
        PanePrincipal.setSelectedComponent(panelGH);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanePrincipal = new javax.swing.JTabbedPane();

        setClosable(true);
        setTitle("Habitaciones");
        setPreferredSize(new java.awt.Dimension(850, 600));

        PanePrincipal.setPreferredSize(new java.awt.Dimension(800, 600));
        jScrollPane1.setViewportView(PanePrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanePrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
